# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yuc < Formula
  desc "YAML Unicode Check - find sketchy unicode characters in YAML configs"
  homepage "https://github.com/harshadixit12/yuc"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harshadixit12/yuc/releases/download/v0.2.2/yuc_darwin_amd64.tar.gz"
      sha256 "d37c05b93a6c193fd679ed0fc7f76daaa3d5b73638203837c67a3f31c6087e5e"

      define_method(:install) do
        bin.install "yuc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harshadixit12/yuc/releases/download/v0.2.2/yuc_darwin_arm64.tar.gz"
      sha256 "563ff5de86aa6272581f7be316e7974976a29b982358fc76e342203c4617298b"

      define_method(:install) do
        bin.install "yuc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harshadixit12/yuc/releases/download/v0.2.2/yuc_linux_amd64.tar.gz"
      sha256 "56b336b07b039a18a24d48868bb9b4043963ee83dd3950e64022041fecb7a5fa"
      define_method(:install) do
        bin.install "yuc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harshadixit12/yuc/releases/download/v0.2.2/yuc_linux_arm64.tar.gz"
      sha256 "9299ba0212ceddbd1934a7f4d9549b49364d8f0bd204e3a53a84e6dd45b63785"
      define_method(:install) do
        bin.install "yuc"
      end
    end
  end

  test do
    system "#{bin}/yuc", "--version"
  end
end
